name: Vocabulary Ingestion Pipeline

on:
  workflow_dispatch:

  schedule:
    # Todo dia às 02:00 UTC (23:00 no Brasil, dependendo do horário de verão)
    - cron: "0 2 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader stopwords

      - name: Run pipeline
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        run: |
          python run.py